######################################################################
# Automatically generated by qmake (3.1) Wed Feb 20 09:45:49 2019
######################################################################
TEMPLATE = lib
TARGET = foo
QT += core
config -= gui
OBJECTS_DIR = obj
includepath += .

HEADERS += foo.h
SOURCES += foo.cpp
DEFINES += LIBFOO_BUILD

linux-*:LIBS += -lrt

target.path = ../lib
INSTALLS += target

# Directories
